# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :mingus do |mingus_config|
	mingus_config.vm.box = 'centos6'
	mingus_config.vm.box_url = 'https://dl.dropbox.com/u/7225008/Vagrant/CentOS-6.3-x86_64-minimal.box' 
	mingus_config.vm.hostname = 'mingus'
	mingus_config.vm.provider :virtualbox do |vb|
		vb.customize ["modifyvm", :id, "--memory", "4096"] 
	end
	mingus_config.vm.network "public_network" 
   end

end
