# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :node do |node_config|
	node_config.vm.box = 'centos6'
	node_config.vm.box_url = 'https://github.com/tommy-muehle/puppet-vagrant-boxes/releases/download/1.0.0/centos-6.6-x86_64.box'
	node_config.vm.hostname = 'issue7-test-node'
	node_config.vm.provision "shell", path: "./provision.sh"
        node_config.vm.network "private_network", ip: "192.168.35.10"
   end

end
