# -*- mode: ruby -*-
# vi: set ft=ruby :

# This boots up the environment used for the Mastering Ansible Udemy course. 

IP_BLOCK="192.168.75"

Vagrant.configure("2") do |config|
  config.vm.box = 'centos65-x86_64-20140116'
  config.vm.box_url = 'https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box'
  config.vm.boot_timeout = 600
  machine_id = 2 
  # Create all nodes identically except for name and ip
  [ 'control', 'lb01', 'app01', 'app02', 'db01' ].each { |name|
    config.vm.define name do |node_config|
      node_config.vm.hostname = name
      node_config.vm.network "private_network", ip: "#{IP_BLOCK}.#{machine_id}"
      machine_id = machine_id + 1
    end
  }
end

