# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :mysql57 do |mysql57_config|
	mysql57_config.vm.box = 'centos6'
	mysql57_config.vm.box_url = 'https://github.com/tommy-muehle/puppet-vagrant-boxes/releases/download/1.0.0/centos-6.6-x86_64.box'
	mysql57_config.vm.hostname = 'mysql57'
	mysql57_config.vm.provider :virtualbox do |vb|
		vb.customize ["modifyvm", :id, "--memory", "1024", "--cpuexecutioncap", "60"] 
	end
	mysql57_config.vm.network "public_network" 
	mysql57_config.vm.provision "shell", path: "./provision.sh"
   end

end
