# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :psfm do |psfm_config|
	psfm_config.vm.box = 'centos6'
	psfm_config.vm.box_url = 'https://dl.dropbox.com/u/7225008/Vagrant/CentOS-6.3-x86_64-minimal.box' 
	psfm_config.vm.hostname = 'psfm'
	psfm_config.vm.provider :virtualbox do |vb|
		vb.customize ["modifyvm", :id, "--memory", "8192"]
	end
        psfm_config.vm.synced_folder "~/src/", "/home/vagrant/src/"
	psfm_config.vm.network "public_network" 
	psfm_config.vm.provision "shell", path: "./provision.sh"
   end

end
