# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :devstack do |devstack_config|
	devstack_config.vm.box = 'centos6'
	devstack_config.vm.box_url = 'https://dl.dropbox.com/u/7225008/Vagrant/CentOS-6.3-x86_64-minimal.box' 
	devstack_config.vm.hostname = 'devstack'
	devstack_config.vm.provider :virtualbox do |vb|
		vb.customize ["modifyvm", :id, "--memory", "1024"] 
	end
	devstack_config.vm.network "public_network" 
	devstack_config.vm.provision "shell", path: "./provision.sh"
   end

end
