# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  #config.vbguest.auto_update = false
  #config.vbguest.no_remote = true
  config.vm.define :miles do |miles_config|
	miles_config.vm.box = 'centos7'
	miles_config.vm.hostname = 'miles'
	miles_config.vm.provider :virtualbox do |vb|
		vb.customize ["modifyvm", :id, "--memory", "4096", "--cpus", "12"] 
	end

        miles_config.vm.synced_folder "~/src/", "/home/vagrant/src/"
	miles_config.vm.network "public_network" 
        miles_config.vm.provision "shell", path: "./provision.sh"
   end

end
