# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :ps56 do |ps56_config|
	ps56_config.vm.box = 'centos6'
	ps56_config.vm.box_url = 'https://dl.dropbox.com/u/7225008/Vagrant/CentOS-6.3-x86_64-minimal.box' 
	ps56_config.vm.hostname = 'ps56'
	ps56_config.vm.provider :virtualbox do |vb|
		vb.customize ["modifyvm", :id, "--memory", "8192", "--cpuexecutioncap", "60", "--cpus", "4"] 
	end
	ps56_config.vm.network "public_network" 
	ps56_config.vm.synced_folder "~/src/", "/home/vagrant/src/"
	ps56_config.vm.provision "shell", path: "./provision.sh"
   end

end
